### ISSUE TITLE
error

### ISSUE THREAD

**Issue by wengxianxun** [Schloool/samba-browser-flutter#1]
E/flutter (28962): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(Can only show list content of folders., null, null, null)
E/flutter (28962): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651:7)
E/flutter (28962): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
E/flutter (28962): <asynchronous suspension>
E/flutter (28962): #2      SambaBrowser.getShareList (package:samba_browser/samba_browser.dart:21:25)
E/flutter (28962): <asynchronous suspension>
E/flutter (28962):

**Comment by muhundhan23** [comment]
Found any solution?

**Comment by muhundhan23** [comment]
@wengxianxun, found any solution for it? Facing the similar kind of issue. And also I saw you in another package error, hope you have found a solution for what we're trying to do here.

**Comment by wengxianxun** [comment]
> @wengxianxun, found any solution for it? Facing the similar kind of issue. And also I saw you in another package error, hope you have found a solution for what we're trying to do here.

NO, not found

**Comment by Schloool** [comment]
@wengxianxun please provide your full code so I can take a closer look.
As stated in the package description, for now the approach is fully experimental which could lead to unexpected errors.

**Comment by santhosh-D-subramani** [comment]
here is the code :
`class _MyHomePageState extends State<MyHomePage> {
  void _fetchSMB() {
    SambaBrowser.getShareList('smb://171.20.10.2/', 'domain.net', 'pc', '123')
        .then((shares) => print('Shares found: ${shares.cast<String>()}'));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('SMB Fetcher'),
      ),
      body: const Text(''),
      floatingActionButton: FloatingActionButton(
        onPressed: _fetchSMB,
        tooltip: 'fetch smb',
        child: const Icon(Icons.add),
      ), 
    );
  }
}`
same error :
E/flutter ( 3045): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(A class jcifs.smb.SmbException occurred., Failed to connect: 0.0.0.0<00>/171.20.10.2, null, null)
E/flutter ( 3045): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651:7)
E/flutter ( 3045): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
E/flutter ( 3045): <asynchronous suspension>
E/flutter ( 3045): #2      SambaBrowser.getShareList (package:samba_browser/samba_browser.dart:21:25)
E/flutter ( 3045): <asynchronous suspension>
E/flutter ( 3045): #3      _MyHomePageState._fetchSMB.<anonymous closure> (package:smb_test/main.dart:41:15)
E/flutter ( 3045): <asynchronous suspension>
E/flutter ( 3045):

**Comment by santhosh-D-subramani** [comment]
here is full code:
```
class _MyHomePageState extends State<MyHomePage> {
  void _fetchSMB() {
    SambaBrowser.getShareList('smb://171.20.10.2/', 'domain.net', 'pc', '123')
        .then((shares) => print('Shares found: ${shares.cast<String>()}'));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('SMB Fetcher'),
      ),
      body: const Text(''),
      floatingActionButton: FloatingActionButton(
        onPressed: _fetchSMB,
        tooltip: 'fetch smb',
        child: const Icon(Icons.add),
      ), 
    );
  }
} 
```
the error: 
```
E/flutter ( 3045): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(A class jcifs.smb.SmbException occurred., Failed to connect: 0.0.0.0<00>/171.20.10.2, null, null)
E/flutter ( 3045): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651:7)
E/flutter ( 3045): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
E/flutter ( 3045): <asynchronous suspension>
E/flutter ( 3045): #2      SambaBrowser.getShareList (package:samba_browser/samba_browser.dart:21:25)
E/flutter ( 3045): <asynchronous suspension>
E/flutter ( 3045): #3      _MyHomePageState._fetchSMB.<anonymous closure> (package:smb_test/main.dart:41:15)
E/flutter ( 3045): <asynchronous suspension>
E/flutter ( 3045): 
```

**Comment by santhosh-D-subramani** [comment]
here's the full code:
```
class _MyHomePageState extends State<MyHomePage> {
  void _fetchSMB() {
    SambaBrowser.getShareList('smb://192._ _._ _.2/', 'domain.net', 'pc', '123')
        .then((shares) => print('Shares found: ${shares.cast<String>()}'));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('SMB Fetcher'),
      ),
      body: const Text(''),
      floatingActionButton: FloatingActionButton(
        onPressed: _fetchSMB,
        tooltip: 'fetch smb',
        child: const Icon(Icons.add),
      ), 
    );
  }
}
```
here's the same error 
```
E/flutter ( 3045): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(A class jcifs.smb.SmbException occurred., Failed to connect: 0.0.0.0<00>/171.20.10.2, null, null)
E/flutter ( 3045): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651:7)
E/flutter ( 3045): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
E/flutter ( 3045): <asynchronous suspension>
E/flutter ( 3045): #2      SambaBrowser.getShareList (package:samba_browser/samba_browser.dart:21:25)
E/flutter ( 3045): <asynchronous suspension>
E/flutter ( 3045): #3      _MyHomePageState._fetchSMB.<anonymous closure> (package:smb_test/main.dart:41:15)
E/flutter ( 3045): <asynchronous suspension>
E/flutter ( 3045): 
```

**Comment by santhosh-D-subramani** [comment]
here's the full code:
```
class _MyHomePageState extends State<MyHomePage> {
  void _fetchSMB() {
    SambaBrowser.getShareList('smb://171.**.**.2/', 'domain.net', 'pc', '123')
        .then((shares) => print('Shares found: ${shares.cast<String>()}'));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('SMB Fetcher'),
      ),
      body: const Text(''),
      floatingActionButton: FloatingActionButton(
        onPressed: _fetchSMB,
        tooltip: 'fetch smb',
        child: const Icon(Icons.add),
      ), 
    );
  }
}
```

same error:
```
E/flutter ( 3045): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(A class jcifs.smb.SmbException occurred., Failed to connect: 0.0.0.0<00>/171.**.**.2, null, null)
E/flutter ( 3045): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651:7)
E/flutter ( 3045): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
E/flutter ( 3045): <asynchronous suspension>
E/flutter ( 3045): #2      SambaBrowser.getShareList (package:samba_browser/samba_browser.dart:21:25)
E/flutter ( 3045): <asynchronous suspension>
E/flutter ( 3045): #3      _MyHomePageState._fetchSMB.<anonymous closure> (package:smb_test/main.dart:41:15)
E/flutter ( 3045): <asynchronous suspension>
E/flutter ( 3045): 
```

**Comment by santhosh-D-subramani** [comment]
Full Code: code from official sambabrowser github , example main.dart
```
import 'package:flutter/material.dart';
import 'package:samba_browser/samba_browser.dart';

void main() {
  runApp(const SambaApp());
}

class SambaApp extends StatefulWidget {
  const SambaApp({Key? key}) : super(key: key);

  @override
  State<SambaApp> createState() => _SambaAppState();
}

class _SambaAppState extends State<SambaApp> {

  String shareUrl = '';
  String domain = '';
  String username = '';
  String password = '';

  Future<List>? shareFuture;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('SAMBA Plugin example app'),
        ),
        body: SingleChildScrollView(
          child: Center(
            child: Padding(
              padding: const EdgeInsets.all(8.0),
              child: Column(
                children: [
                  TextFormField(
                    onChanged: (text) => shareUrl = text,
                    decoration: const InputDecoration(
                      border: UnderlineInputBorder(),
                      labelText: 'SAMBA share URL',
                    ),
                  ),

                  TextFormField(
                    onChanged: (text) => domain = text,
                    decoration: const InputDecoration(
                      border: UnderlineInputBorder(),
                      labelText: 'Domain',
                    ),
                  ),

                  Row(
                    children: [
                      Flexible(
                        child: TextFormField(
                          onChanged: (text) => username = text,
                          decoration: const InputDecoration(
                            border: UnderlineInputBorder(),
                            labelText: 'Username',
                          ),
                        ),
                      ),
                      const SizedBox(width: 15.0),
                      Flexible(
                        child: TextFormField(
                          onChanged: (text) => password = text,
                          obscureText: true,
                          decoration: const InputDecoration(
                            border: UnderlineInputBorder(),
                            labelText: 'Password',
                          ),
                        ),
                      ),
                    ],
                  ),

                  TextButton(
                    onPressed: () => setState(() {
                      shareFuture = SambaBrowser.getShareList(shareUrl, domain, username, password);
                    }),
                    child: const Text("List available shares")
                  ),

                  const SizedBox(height: 30.0),

                  if (shareFuture != null) FutureBuilder(future: shareFuture, builder: (context, snapshot) {
                    if (snapshot.hasError) {
                      return Column(
                      children: [
                        const Text('An error has occurred.'),
                        Text(snapshot.error.toString())
                      ]);
                    }

                    if (!snapshot.hasData) return const CircularProgressIndicator();

                    List<String> shares = (snapshot.data as List).cast<String>();
                    return Column(children: shares.map((e) => Text(e)).toList());
                  })
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```
SMB server: shared a folder from windows file manager (accessible in other java smb connector applications)

error: same error as @wengxianxun mentioned

**Comment by santhosh-D-subramani** [comment]
@wengxianxun i checked the package :

    
```
 String url = call.argument("url");
        if (!url.endsWith("/")) {
            result.error("Can only show list content of folders.", null, null);
            return;
        }
```

you need to add a "/" in the end of url to get it working.

**Comment by Schloool** [comment]
@santhosh-D-subramani thank you for looking into it, that is indeed correct. Maybe I will add an auto-transformation of the URL at some time.
