### ISSUE TITLE
A class jcifs.smb.SmbException occurred., Failed to connect: 0.0.0.0<00>/192.168.31.36, null, null)

### ISSUE THREAD

**Issue by swithun-liu** [Schloool/samba-browser-flutter#3]
E/flutter (31299): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(A class jcifs.smb.SmbException occurred., Failed to connect: 0.0.0.0<00>/192.168.31.36, null, null)
E/flutter (31299): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651:7)
E/flutter (31299): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:322:18)
E/flutter (31299): <asynchronous suspension>
E/flutter (31299): #2      SambaBrowser.getShareList (package:samba_browser/samba_browser.dart:21:25)
E/flutter (31299): <asynchronous suspension>
E/flutter (31299): #3      SmbFileRepo.getDirectory.<anonymous closure> (package:x_plore_remote_ui/repo/v2/SmbaFileRepo.dart:18:11)
E/flutter (31299): <asynchronous suspension>

```kotlin
    SambaBrowser.getShareList('smb://192.168.31.36/', 'domain.net', '', '')
    .then((shares) => logger.d('[SmbFileRepo] [getDirectory] ${shares.cast<String>()}'))
    ;
    return [];
```

**Comment by spechtnathan** [comment]
Hello, I had the same problem, I tried to switch the minimum protocol to SMB1 on my NAS and it works. (SMB1 is deprecated so don't use this plugin)
